/*
 * CODENVY CONFIDENTIAL
 * __________________
 * 
 *  [2012] - [2014] Codenvy, S.A. 
 *  All Rights Reserved.
 * 
 * NOTICE:  All information contained herein is, and remains
 * the property of Codenvy S.A. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Codenvy S.A.
 * and its suppliers and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Codenvy S.A..
 */
package com.codenvy.auth.sso.server;


import com.codenvy.api.core.ApiException;
import com.codenvy.api.core.ConflictException;
import com.codenvy.api.core.NotFoundException;
import com.codenvy.api.core.ServerException;
import com.codenvy.api.user.server.Constants;
import com.codenvy.api.user.server.dao.Profile;
import com.codenvy.api.user.server.dao.UserDao;
import com.codenvy.api.user.server.dao.UserProfileDao;
import com.codenvy.auth.sso.server.organization.UserCreator;
import com.codenvy.commons.lang.NameGenerator;
import com.codenvy.commons.user.User;
import com.codenvy.commons.user.UserImpl;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Inject;
import java.io.IOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * @author Sergii Kabashniuk
 */
public class OrgServiceUserCreator implements UserCreator {
    private static final Logger LOG = LoggerFactory.getLogger(OrgServiceUserCreator.class);

    @Inject
    private UserDao userDao;

    @Inject
    private UserProfileDao profileDao;

    @Override
    public User createUser(String userName, String firstName, String lastName) throws IOException {
        //TODO check this method should only call if user is not exists.
        try {
            com.codenvy.api.user.server.dao.User user = userDao.getByAlias(userName);
            return new UserImpl(userName, user.getId(), null, Collections.<String>emptyList(), false);
        } catch (NotFoundException e) {
            String id = NameGenerator.generate(User.class.getSimpleName().toLowerCase(), Constants.ID_LENGTH);
            Map<String, String> attributes = new HashMap<>();
            attributes.put("firstName", firstName);
            attributes.put("lastName", lastName);
            attributes.put("codenvy:created", Long.toString(System.currentTimeMillis()));
            attributes.put("resetPassword", "true");

            Profile profile = new Profile()
                    .withId(id)
                    .withUserId(id)
                    .withAttributes(attributes);
            String password = UUID.randomUUID().toString().replace("-", "").substring(0, 12);

            try {
                userDao.create(new com.codenvy.api.user.server.dao.User().withId(id)
                                                                         .withEmail(userName)
                                                                         .withPassword(password));
                profileDao.create(profile);
                return new UserImpl(userName, id, null, Collections.<String>emptyList(), false);
            } catch (ConflictException | ServerException e1) {
                throw new IOException(e1.getLocalizedMessage(), e1);
            }
        } catch (ServerException e) {
            throw new IOException(e.getLocalizedMessage(), e);
        }

    }

    @Override
    public User createTemporary() throws IOException {

        String id = NameGenerator.generate(User.class.getSimpleName(), Constants.ID_LENGTH);
        try {
            String testName = null;
            while (true) {
                testName = NameGenerator.generate("AnonymousUser_", 6);
                try {
                    userDao.getByAlias(testName);
                } catch (NotFoundException e) {
                    break;
                } catch (ApiException e) {
                    throw new IOException(e.getLocalizedMessage(), e);
                }

            }


            final String anonymousUser = testName;
            // generate password and delete all "-" symbols which are generated by randomUUID()
            String password = UUID.randomUUID().toString().replace("-", "").substring(0, 12);


            userDao.create(new com.codenvy.api.user.server.dao.User().withId(id).withEmail(anonymousUser)
                                                                     .withPassword(password));
            Map<String, String> attributes = new HashMap<>();
            attributes.put("temporary", String.valueOf(true));
            attributes.put("codenvy:created", Long.toString(System.currentTimeMillis()));
            profileDao.create(new Profile()
                                      .withId(id)
                                      .withUserId(id)
                                      .withAttributes(attributes));
            LOG.info("Temporary user {} created", anonymousUser);
            return new UserImpl(anonymousUser, id, null, Collections.<String>emptyList(), true);
        } catch (ApiException e) {
            throw new IOException(e.getLocalizedMessage(), e);
        }
    }
}
