# Copyright (c) 2016 Codenvy, S.A.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# build:
#   docker build -t codenvy/puppet:<version> .
#
# use:
#    docker run codenvy/puppet:<version>

FROM puppet/puppet-agent-alpine:4.6.2
RUN apk --update add openssh

