/*
 *    Copyright (C) 2013 Codenvy.
 *
 */
package com.codenvy.analytics.metrics;

/**
 * @author <a href="mailto:abazko@codenvy.com">Anatoliy Bazko</a>
 */
public enum MetricType {
    WORKSPACES_CREATED,
    WORKSPACES_DESTROYED,
    TOTAL_WORKSPACES,
    ACTIVE_WORKSPACES,
    PERCENT_ACTIVE_WORKSPACES,
    PERCENT_INACTIVE_WORKSPACES,
    USERS_CREATED,
    USERS_CREATED_PROJECTS,
    PERCENT_USERS_CREATED_PROJECTS,
    USERS_DESTROYED,
    TOTAL_USERS,
    ACTIVE_USERS,
    PERCENT_ACTIVE_USERS,
    PERCENT_INACTIVE_USERS,
    USERS_ADDED_TO_WORKSPACE,
    USERS_ADDED_TO_WORKSPACE_FROM_WEBSITE,
    USERS_ADDED_TO_WORKSPACE_FROM_INVITE
}
