/*
 *    Copyright (C) 2013 Codenvy.
 *
 */
package com.codenvy.analytics.metrics;

/**
 * @author <a href="mailto:abazko@codenvy.com">Anatoliy Bazko</a>
 */
public enum MetricType {
    WORKSPACES_CREATED,
    WORKSPACES_DESTROYED,
    TOTAL_WORKSPACES,
    ACTIVE_WORKSPACES,
    PERCENT_ACTIVE_WORKSPACES,
    PERCENT_INACTIVE_WORKSPACES,
    USERS_CREATED,
    USERS_CREATED_PROJECTS,
    PERCENT_USERS_CREATED_PROJECTS,
    USERS_DESTROYED,
    TOTAL_USERS,
    ACTIVE_USERS,
    PERCENT_ACTIVE_USERS,
    PERCENT_INACTIVE_USERS,
    USERS_ADDED_TO_WORKSPACE,
    USERS_ADDED_TO_WORKSPACE_FROM_WEBSITE,
    USERS_ADDED_TO_WORKSPACE_FROM_INVITE,
    USERS_SSO_LOGGED_IN,
    USERS_SSO_LOGGED_IN_USING_GOOGLE,
    USERS_SSO_LOGGED_IN_USING_GITHUB,
    USERS_SSO_LOGGED_IN_USING_FORM,
    PRODUCT_USAGE_TIME,
    PROJECTS_CREATED,
    PROJECTS_DESTROYED,
    TOTAL_RPOJECTS,
    PROJECT_CREATED_TYPES,
    PROJECT_TYPE_JAVA_JAR,
    PROJECT_TYPE_JAVA_WAR,
    PROJECT_TYPE_JAVA_JSP,
    PROJECT_TYPE_JAVA_SPRING,
    PROJECT_TYPE_PHP,
    PROJECT_TYPE_PYTHON,
    PROJECT_TYPE_JAVASCRIPT,
    PROJECT_TYPE_RUBY,
    PROJECT_TYPE_MMP,
    PROJECT_TYPE_GROOVY,
    PROJECT_TYPE_OTHERS,
}
