box      = 'gwhorley/rhel72-x86_64'

ram      = '8096'
cpus     = '4'
bridge   = 'eth0'

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.ssh.insert_key = false
  config.vm.network :private_network, ip: "192.168.56.110"
  config.vm.network "forwarded_port", guest: 5005, host: 5005

  config.vm.provider :virtualbox do |vbox|
    vbox.customize [
        'modifyvm', :id,
        '--memory', ram,
        '--cpus', cpus
    ]
  end

  # Register RHEL subscription
  $script = <<-SHELL
  sudo subscription-manager register --username riuvshin@codenvy.com --password codenvy --auto-attach
  sudo subscription-manager repos --enable=rhel-7-server-optional-rpms
  sudo subscription-manager repos --enable=rhel-7-server-extras-rpms

  sudo yum install net-tools -y
  SHELL

  config.vm.provision "shell", inline: $script

  # Adding hosts rules
  config.vm.provision "shell", inline: "echo -e \"127.0.0.1 localhost\" > /etc/hosts"
  config.vm.provision "shell", inline: "echo -e \"nameserver 8.8.8.8\n\" >> /etc/resolv.conf"
end
